### ISSUE TITLE
Obsolete stuff in the repository

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython-sigfox#117]
This repository contains a lot of stuff, which is not needed, just to mention a few of the TLD's:
bare-arm
cc3200
docs
esp8266
examples
logo
minimal
pic16bit
qemu-arm
~~stmha~~l
teensy
unix
windows
zephyr

They could be removed.

**Comment by Xykon** [comment]
Some of these can definitely be removed but I believe we are using some code from the stmhal directory. I'll talk to @danicampora to see what he thinks.

**Comment by robert-hh** [comment]
I made a test-clean and build (for LoPy) yesterday. There are indeed a few files in stmhal and a the sx127x subdir in drivers which were needed. Some others, like in examples or drivers/display, may still be useful. But without verification they create more confusion than help.

**Comment by Xykon** [comment]
Sorry it took a while to get back on this, I had a discussion with Daniel at the time and we decided to keep the entire micropython project as is. You should consider this as a snapshot of the official micropython repository with modifications made to support our boards, rather than a firmware specifically for our (or generic) esp32 boards.

**Comment by robert-hh** [comment]
That may be ok. But the question is: snapshot of what? The micropython.org repository has developed a lot since then, and there is also the Loboris branch, which is widely used. So effectively it is a firmware version specifically for Pycom's boards.
