### ISSUE TITLE
_thread.start_new_thread fails to return to main, on start if arg list is missing

### ISSUE THREAD

**Issue by gregcope** [pycom/pycom-micropython-sigfox#158]
MicroPython v1.8.6-849-83e2f7f on 2018-03-19; GPy with ESP32

* Exact steps to cause this issue
Call _thread.start_new_thread with a function that takes no arguments, without supplying an empty list thus;

self.gps_thread = _thread.start_new_thread(self.feedMicroGPS)

It works if I do this;

self.gps_thread = _thread.start_new_thread(self.feedMicroGPS,())

* What you expected
Calling a _thread.start_new_thread with a function, which takes no args, should return with new thread ID if called without any args - ie empty list should not be required.

* What happened instead
thread starts, but never returns.  Main hangs.

If it needs/expects an empty list it should throw an exception or accept no args and return.  Not hang main.

**Comment by Sympatron** [comment]
When I try to call `start_new_stread()` with just one argument I get the following exception:

    TypeError: function missing 1 required positional arguments

Which makes sence since the following line states that at least 2 arguments are expected:
https://github.com/pycom/pycom-micropython-sigfox/blob/7c0b7976f805eb999b8d0cdb4e31c1ad8abc4e1c/py/modthread.c#L257

Are you sure you use the latest version?

**Comment by gregcope** [comment]
Will need to check versions...
