### ISSUE TITLE
Issue with pycom-micropython-sigfox compilation for ESP32

### ISSUE THREAD

**Issue by limartin1** [pycom/pycom-micropython-sigfox#168]
Hello,

I want to manually compile the firmware for my Pycom (SiPy) module in order to put code in the frozen zone. For the moment I can not do it. I am on Linux Fedora. I followed the installation tutorial of the toolchain xtensa-esp32-elf- and I cloned the reposity pycom-esp-idf, with the submodules installed. I manage to compile without problem the example hello-world present in pycom-esp-idf / examples / get-started / so a priori I have no problem with the toolchain or with pycom-esp-idf. By cons when I want to use the repository pycom-micropython-sigfox it does not work. I can compile the mpy-cross folder successfully. But I can not compile the esp32 folder. I put you the result of the compilation:

[lilian@localhost esp32]$ make all
Use make SECURE=on [optionally SECURE_KEY ?= secure_boot_signing_key.pem] to enable Secure Boot and Flash Encryption mechanisms.
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
mkdir -p build/SIPY/release/genhdr
Create build/SIPY/release/genhdr/pins.h
Generating build/SIPY/release/genhdr/mpversion.h
GEN build/SIPY/release/genhdr/qstr.i.last
**In file included from mods/modwlan.c:46:0:
mods/modussl.h:19:25: fatal error: mbedtls/net.h: No such file or directory
compilation terminated.
In file included from mods/modussl.c:28:0:
mods/modussl.h:19:25: fatal error: mbedtls/net.h: No such file or directory
compilation terminated.
mods/modbt.c:16:24: fatal error: controller.h: No such file or directory
compilation terminated.
In file included from mods/lwipsocket.c:32:0:
mods/modussl.h:19:25: fatal error: mbedtls/net.h: No such file or directory
compilation terminated.**
make: *** [../py/mkrules.mk:74: build/SIPY/release/genhdr/qstr.i.last] Error 1
make: *** Suppression du fichier « build/SIPY/release/genhdr/qstr.i.last »
[lilian@localhost esp32]$ 

I think the compiler does not find the dependencies mbedtls nor controller.h. Is there anything to change in the makefile? Or can be a bug in the repository?

Thank you in advance,

Lilian

**Comment by iwahdan88** [comment]
Hi @limartin1, We are working on a new development firmware which we are planning to release early next week, due to this the  'pycom-micropython-sigfox' is not building against the HEAD of 'pycom-esp-idf' since it was updated to sync with the latest espressif IDF, in the mean time you can build the  'pycom-micropython-sigfox' against tag/release '1.18.0' in 'pycom-eps-idf'
`git clone https://github.com/pycom/pycom-esp-idf.git 1.18.0`
or checkout the corresponding commit
`git checkout 4eab4e1b0e47c73b858c6b29d357f3d30a69c074`
and
`git submodule update`

This will make sure you are using the correct IDF version for the current stable release.

**Comment by limartin1** [comment]
Thank you very much !! Everything is working !
