### ISSUE TITLE
FTP Server Functionality

### ISSUE THREAD

**Issue by innoagg** [pycom/pycom-micropython-sigfox#212]
Pycom MicroPython 1.18.1.r1 [v1.8.6-849-b0520f1] on 2018-08-29; GPy with ESP32

The FTP server does not function properly concerning the PASV command and the command response. When the WLAN is in STA mode the server will reply with the local IP. When in AP or STA_AP mode the IP will be 0.0.0.0.

The FTP server is responsible for giving a proper, or expected, IP address to the client. Many clients will implement rules about receiving invalid or unroutable IP's, but returning 0.0.0.0 as the address will cause most to fail. 

Yes, the WLAN.ifconfig() can be used to set a specific IP, however when in STA_AP this causes issues. When in STA_AP mode is not not clear what the IP of the AP is. WLAN.ifconfig() returns 0.0.0.0. Setting the WLAN.ifconfig() for the purposes of the FTP will have the consequence of making the AP not function properly.

I recommend as a solution that the firmware enable a fixed IP to be set for the FTP server to respond appropriately to the PASV command. This is consistent with most FTP servers functionality.

I also recommend that the AP's gateway IP address be available for consumption if it not fixed as 192.168.4.1.

**Comment by iwahdan88** [comment]
Hello @innoagg 

This reason behind this problem was that when using wifi in STA_AP mode the `bind()` function would always bind ftp socket to STA IP address , so if you are in STA_AP mode you have AP IP = `192.168.4.1` and depending on weather your STA is connected to a WIFI and acquired an IP or not you will get `PASV` response = `0.0.0.0` if not connected and '<STA_IP>' if connected. which is a problem.

This problem is solved currently in the Development Firmware `1.19.0.b4` and will be merged later as stable. where you can have pycom module having 2 separate Interfaces for STA and AP and can serve FTP client `PASV` commands with the Correct IP.

I will close this Issue , but you can reopen if you find that it Is still not Solved.
